# Generated by Django 5.1.2 on 2024-10-24 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebites', '0002_product_sharebites_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharebites',
            name='product',
        ),
        migrations.RenameField(
            model_name='sharebites',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='sharebites',
            old_name='food_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sharebites',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='sharebites',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='sharebites',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sharebites',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='sharebites',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='sharebites',
            name='sugar_content',
        ),
        migrations.AddField(
            model_name='sharebites',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sharebites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sharebites.sharebites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sharebites.sharebites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
