# Generated by Django 5.1.2 on 2024-10-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebites', '0005_remove_sharebites_author_sharebites_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharebites',
            name='calorie_content',
            field=models.CharField(choices=[('low', 'Low Calorie'), ('high', 'High Calorie')], default='low', max_length=4),
        ),
        migrations.AddField(
            model_name='sharebites',
            name='diet_type',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('non_vegan', 'Non-Vegan')], default='non_vegan', max_length=10),
        ),
        migrations.AddField(
            model_name='sharebites',
            name='sugar_content',
            field=models.CharField(choices=[('low', 'Low Sugar'), ('high', 'High Sugar')], default='low', max_length=4),
        ),
    ]
