# Generated by Django 5.1.1 on 2024-10-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
