# Generated by Django 5.1.2 on 2024-10-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerBites', '0002_alter_bitetrackermodel_bite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitetrackermodel',
            name='bite_time',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10),
        ),
    ]
