# Generated by Django 5.1.2 on 2024-10-22 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('nama_product', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('tag_kalori', models.CharField(choices=[('tinggi', 'Tinggi Kalori'), ('rendah', 'Rendah Kalori')], max_length=6)),
                ('tag_vegan', models.CharField(choices=[('vegan', 'Vegan'), ('non-vegan', 'Non-Vegan')], max_length=9)),
                ('tag_gula', models.CharField(choices=[('tinggi', 'Tinggi Gula'), ('rendah', 'Rendah Gula')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MyBites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBites.product')),
            ],
        ),
    ]
