# Generated by Django 5.1.2 on 2024-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kalori',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
