# Generated by Django 5.1.2 on 2024-10-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBites', '0002_product_kalori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nama_toko',
            new_name='nama_toko_lokasi',
        ),
    ]
