# Generated by Django 5.1.2 on 2024-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('BookTitle', models.CharField(max_length=255)),
                ('BookAuthor', models.CharField(max_length=255)),
                ('Year_Of_Publication', models.PositiveIntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('Image', models.URLField()),
            ],
        ),
    ]
