# Generated by Django 5.1.1 on 2024-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editbites', '0002_rename_created_at_article_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('BookTitle', models.CharField(max_length=255)),
                ('BookAuthor', models.CharField(max_length=255)),
                ('Year_Of_Publication', models.PositiveIntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('Image', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
