# Generated by Django 5.1 on 2024-10-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editbites', '0003_alter_product_options_alter_product_calorie_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['store', 'name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='calorie_tag',
            field=models.CharField(choices=[('HIGH', 'Tinggi'), ('LOW', 'Rendah')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('QITA_MART', 'QITA MART, Jl. K.H.M. Usman No.38, Kukusan, Kecamatan Beji, Kota Depok, Jawa Barat 16425'), ('TUTUL_V_MARKET', 'Tutul V Market, Jl. Margonda No.358, Kemiri Muka, Kecamatan Beji, Kota Depok, Jawa Barat 16423'), ('AL_HIKAM_MART', 'Al Hikam Mart, Jl. H. Amat No.21, Kukusan, Kecamatan Beji, Kota Depok, Jawa Barat 16425'), ('SNACK_JAYA_MARKET', 'Snack Jaya Market, Jl. Cagar Alam Sel. No.60, RT.01/RW.02, Pancoran MAS, Kec. Pancoran Mas, Kota Depok, Jawa Barat 16436'), ('BELANDA_MART', 'Belanda Mart, Jl. Tole Iskandar No.3, Mekar Jaya, Kec. Sukmajaya, Kota Depok, Jawa Barat 16411')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar_tag',
            field=models.CharField(choices=[('HIGH', 'Tinggi'), ('LOW', 'Rendah')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegan_tag',
            field=models.CharField(choices=[('VEGAN', 'Vegan'), ('NON_VEGAN', 'Non-vegan')], max_length=9),
        ),
    ]
